// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKaE2NuvH8Xsn8AOgO7_fkw6eUI8neUyQ',
    appId: '1:1079574665614:web:0803b8d9bca13e23c7acdf',
    messagingSenderId: '1079574665614',
    projectId: 'nutrifit-database',
    authDomain: 'nutrifit-database.firebaseapp.com',
    storageBucket: 'nutrifit-database.firebasestorage.app',
    measurementId: 'G-KZVW7LREW0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY12d9MwDvgZDglZNyufg-3chTVQ3wLXM',
    appId: '1:1079574665614:ios:244d207bc025c1cdc7acdf',
    messagingSenderId: '1079574665614',
    projectId: 'nutrifit-database',
    storageBucket: 'nutrifit-database.firebasestorage.app',
    iosBundleId: 'com.example.nutrifit',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY12d9MwDvgZDglZNyufg-3chTVQ3wLXM',
    appId: '1:1079574665614:ios:244d207bc025c1cdc7acdf',
    messagingSenderId: '1079574665614',
    projectId: 'nutrifit-database',
    storageBucket: 'nutrifit-database.firebasestorage.app',
    iosBundleId: 'com.example.nutrifit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKaE2NuvH8Xsn8AOgO7_fkw6eUI8neUyQ',
    appId: '1:1079574665614:web:84e8673547d0ce21c7acdf',
    messagingSenderId: '1079574665614',
    projectId: 'nutrifit-database',
    authDomain: 'nutrifit-database.firebaseapp.com',
    storageBucket: 'nutrifit-database.firebasestorage.app',
    measurementId: 'G-MRQ1KH17RF',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5uUfIrFWE6fGpgQxPnqfVlEhc79JHadM',
    appId: '1:1079574665614:android:3f481fb9a46d8c25c7acdf',
    messagingSenderId: '1079574665614',
    projectId: 'nutrifit-database',
    storageBucket: 'nutrifit-database.firebasestorage.app',
  );
}
