// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcSMWkEyMn27dpUejeFlaZeibqWhzrRPo',
    appId: '1:318038496829:web:d36f8af3b9a0b6bbc03c54',
    messagingSenderId: '318038496829',
    projectId: 'nutrifit-project-2026',
    authDomain: 'nutrifit-project-2026.firebaseapp.com',
    storageBucket: 'nutrifit-project-2026.firebasestorage.app',
    measurementId: 'G-WBEBV9E0J7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxhgZMHT6pFNoAaXDAutxkmzJbJUK7Vo',
    appId: '1:318038496829:ios:5e6041f0f1825bbcc03c54',
    messagingSenderId: '318038496829',
    projectId: 'nutrifit-project-2026',
    storageBucket: 'nutrifit-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.nutrifit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUxhgZMHT6pFNoAaXDAutxkmzJbJUK7Vo',
    appId: '1:318038496829:ios:5e6041f0f1825bbcc03c54',
    messagingSenderId: '318038496829',
    projectId: 'nutrifit-project-2026',
    storageBucket: 'nutrifit-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.nutrifit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcSMWkEyMn27dpUejeFlaZeibqWhzrRPo',
    appId: '1:318038496829:web:af7b45d7e4b336c4c03c54',
    messagingSenderId: '318038496829',
    projectId: 'nutrifit-project-2026',
    authDomain: 'nutrifit-project-2026.firebaseapp.com',
    storageBucket: 'nutrifit-project-2026.firebasestorage.app',
    measurementId: 'G-6JVF6MWK0X',
  );
}
